### PR TITLE
Add .clap

### LINKED ISSUE #44: Make clap command
Make 👏 a 👏 command 👏 that 👏 will 👏 replace 👏 the 👏 spaces 👏 in 👏 the 👏 string 👏 given 👏 with 👏 the 👏 clap 👏 emoji

### PR DESCRIPTION
**Pull request by emmiegit**
Fix #44

### CODE REVIEW

**Comment by jchristgit** [comment]
👏 simply👏 amazing👏 good👏 work👏 !👏

**Review by Ma-wa-re — APPROVED** [review]
THANK 👏 YOU 👏 FRIEND

**Comment by emmiegit** [comment]
@Volcyy How would you write it?

**Comment by jchristgit** [comment]
like i just did

**Comment by emmiegit** [comment]
Oh I misunderstood you. No love for `map()` I guess.

**Pull request merged**
